### ISSUE TITLE
Sublime freezing while building

### ISSUE THREAD

**Issue by jbaf** [blitzrk/sublime_libsass#17]
Hello again.
I'll just report a minor non-blocking bug here, but quite an anoying one in time : 
On big projects, sublime happen to completeley freeze while building. It comes back to normal after that, but it kinda slows the workflow down...
I don't know what can cause this. If you have any idea.

Thank you.

**Comment by blitzrk** [comment]
Yep, I had been hoping that libsass would be fast enough that I wouldn't need to deal with threading, but it's probably a bigger issue in Windows. Hopefully Sublime has a good API for this, because Python isn't really made for this and it has to be handled at Sublime's native C++ level, anyway.

I'll try to have something working later this week.

**Comment by blitzrk** [comment]
Alright, that was easier than imagined. When PC updates the plugin to 0.9.9, can you let me know how it works on your large project?

**Comment by blitzrk** [comment]
It just updated, in case you're still at work.

**Comment by jbaf** [comment]
Great work, no more freeze !
You rock.

**Comment by blitzrk** [comment]
Thanks for helping to motivate me off my lazy butt! Haha.
