### ISSUE TITLE
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

### ISSUE THREAD

**Issue by knkevinlai** [blitzrk/sublime_libsass#18]
Hi,

Thank you for your work. I get an error when compile scss today which did not happen yesterday:

Exception in thread Thread-6:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\compile.py", line 112, in run
  File ".\libsass\project.py", line 106, in config_for
  File ".\libsass\project.py", line 11, in user_config
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

Environment:
Windows 10, Sublime Text 2.0.2

Regards,
Kevin

**Comment by blitzrk** [comment]
Hey Kevin,

Thank you very much for reporting this! I'm really sorry the latest update broke functionality for you. The change that caused this bug allows for faster and more responsive compilation of ST3. Since I don't want to revert those improvements, I'm going to have to look into splitting this package into ST2 and ST3 branches, but that change will be dependent on the maintainers of Package Control approving it, so it could be a little while.

Meanwhile, I will look into finding a way to reintroduce ST2/ST3 compatibility, if only temporarily, so that you can get back to using this plugin. (Upgrading to ST3 should fix this problem immediately, also.) And thanks so much for using my plugin.

-Ben

**Comment by blitzrk** [comment]
With that said, I actually found a pretty good compromise that shouldn't noticeably affect performance on ST3. Version 0.9.10 should be out in the next hour. When you confirm that the problem has been fixed for you, I'll close this issue.

Enjoy!

**Comment by blitzrk** [comment]
Oh, and if you're happy with my solution, would you mind starring this project? I'm on the job hunt, so every little bit helps. :) Thanks!

**Comment by knkevinlai** [comment]
Hi Blitzrk,

Thank you very much for your response.
v0.9.10 has been upgraded, but another error caught: 

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
    return self.run(**args)
  File ".\compile.py", line 64, in run
  File ".\compile.py", line 108, in **init**
NameError: global name 'file_path' is not defined

Meanwhile I am not able to switch to ST3 yet, but I am fine to use the old version if it take some time for you to fix it (But sorry I dont know where to get it)

Thank you again for your work (project starred***)

**Comment by blitzrk** [comment]
Sorry guys, made a stupid typo. Should be updated in a few minutes. I'm working on unit tests to end this nonsense, but they're non-trivial to set up, because Sublime is proprietary. Thanks for your patience.

**Comment by jbaf** [comment]
It works great again once updated to 0.9.11. Thanks !

**Comment by blitzrk** [comment]
Phew. Okay, so I'll be adding tests this week so it hopefully never regresses from here.

:)
