### ISSUE TITLE
Issue with partials

### ISSUE THREAD

**Issue by ghost** [blitzrk/sublime_libsass#5]
Thanks for reworking on it. Really appreciate the work you did.

But there are few issues and suggestions that I got :-

Issues :- 
1. It is creating a build folder every time a partial file is compiled which should not happen. Partial files should be avoided from compiling .
2. When a partial file is edited and saved, it should compile only those SCSS files in which that partial is included which is not happening right now. 
As a result, making changes in partial file later will not reflect those changes in the scss files in which it is included. Changes reflect only when we compile the main scss files in which they are included.
3. Error messages not coming while compiling partial files.

Suggestions :- 
1. Rather than showing alert box every time, it will be better if you show the errors or even successful compilation messages in console just like sass build. Alert boxes coming while coding is not good. Have to close them every time.

I am attaching the screenshot of a folder structure that is getting this issues.

![scss-structure](https://cloud.githubusercontent.com/assets/8787999/13196318/b441f78a-d7f0-11e5-9f1c-961723d988c4.jpg)

In both landing.scss and common.scss, I have included partial file just for testing.

Can you please have a look ?

**Comment by ghost** [comment]
Also, rather than maintaining a different .libsass.json file for each project, can we have something like other packages where there is a .user and .default file, so that we can edit .user file and can have same settings for all projects ?

**Comment by blitzrk** [comment]
Thank for testing it for me! Let me describe what's going on first and then how I plan to address each problem.
1. This is caused by not having a config file. It guesses that the folder you are in (e.g. atoms) is the root directory for the project and makes an output folder before starting to compile. However, in your case, it will only look in atoms (and deeper) and not find any files requiring it, so there shouldn't be any css files in `styles/atoms/build/css`.
2. It should only be compiling the non-partial files that require a partial if you try to build a partial. If you have more details on a case where that is not the case let me know.
3. They do for me. Any chance you could give me a more specific breakdown of your layout so I can test it?
4. I thought the extra enter press might be a problem.
5. I originally didn't do this, because due to the limitations seen in answer 1, the per-project settings were needed anyway to dictate the top level of the project.

So here's what I'm changing right now.
- [x] I will guess the root of the project more intelligently by looking for the outermost parent with a `.sass` or `.scss` file.
- [x] There will be a user settings file that overrides the defaults, but can be overridden still by a per-project .libsass.json. Between this and the previous change, per-project configs shouldn't be needed very often.
- [x] Compilation success messages will be shown in the status bar for 5 seconds.

Also, I'll check on errors in partials not working, but I think for you this problem stemmed from the unexpected behavior you got by not having a config file. Hopefully once I make the behavior less surprising, you'll see it just works!

Thank you, number 1 user!

**Comment by blitzrk** [comment]
Fixed everything in Release 7.4. Not sure how often PC checks GitHub for updates. Maybe try again in an hour? Or you could add `"repositories": ["https://github.com/blitzrk/sublime_libsass"]`, remove `Libsass Build`, and install the `sublime_libsass` package to test it immediately.
